# prom-nodeport.yaml
grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 32000 # Porta que ficará aberta na AWS
    port: 80
    targetPort: 3000
prometheus:
  service:
    type: NodePort
    nodePort: 32090
alertmanager:
  enabled: true
  service:
    type: NodePort
    nodePort: 32093