resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

# Injeção direta no container ignorando arquivos YAML internos
extraEnvs:
  - name: ELASTICSEARCH_HOSTS
    value: "https://elasticsearch-master:9200"
  - name: ELASTICSEARCH_USERNAME
    value: "elastic"
  - name: ELASTICSEARCH_PASSWORD
    value: "+5SjaYv_Uz-t8WEz5nEF"
  - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
    value: "none"
  - name: XPACK_SECURITY_ENCRYPTIONKEY
    value: "12345678901234567890123456789012"
  - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
    value: "12345678901234567890123456789012"
  - name: XPACK_REPORTING_ENCRYPTIONKEY
    value: "12345678901234567890123456789012"

service:
  type: NodePort
  nodePort: 32561