resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

kibanaConfig:
  kibana.yml: |
    server.host: "0.0.0.0"
    elasticsearch.hosts: ["https://elasticsearch-master:9200"]
    # NOVO TOKEN GERADO ABAIXO
    elasticsearch.serviceAccountToken: "AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbi13ZWI6RlhSbHB1bWRRRXFud2twb1dsdm9rdw"
    elasticsearch.ssl.verificationMode: none

service:
  type: NodePort
  nodePort: 32561